<?xml version="1.0"?>
<package format="3">
  <name>rov_gamantaray_gazebo</name>
  <version>0.1.0</version>
  <description>Gazebo world and mission assets for the KKI-style ROV simulation.</description>
  <maintainer email="ammar@example.com">Ammar</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
  </export>
</package>

